services:
  local-ubuntu-1:
    restart: always
    build: .
    # build:
      # context: ./local/ubuntu
      # dockerfile: Dockerfile
    image: local-ubuntu-image-1:latest
    ports:
      - "2222:22"
    volumes:
      - ./data:/data
      - ./ssh:/root/.ssh
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env.local-ubuntu-1
      - .env.ubuntu


  local-ubuntu-2:
    restart: always
    build: .
    image: local-ubuntu-image-2:latest
    ports:
      - "2223:22"
    volumes:
      - ./data:/data
      - ./ssh:/root/.ssh
    networks:
      - my-network
    depends_on:
      - local-ubuntu-1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"  
    env_file:
      - .env.local-ubuntu-2
      - .env.ubuntu        

  local-ubuntu-3:
    restart: always
    build: .
    image: local-ubuntu-image-3:latest
    ports:
      - "2224:22"    
    volumes:
      - ./data:/data
      - ./ssh:/root/.ssh
    networks:
      - my-network
    depends_on:
      - local-ubuntu-1
      - local-ubuntu-2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        # reservations:
        #   cpus: '0.0001'
        #   memory: 20M      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"     
    env_file:
      - .env.local-ubuntu-3
      - .env.ubuntu           

networks:
  my-network:
    external: true
  # my-overlay-network:
  #   driver: overlay 
    

