services:
  local-centos-1:
    restart: always
    # build: .
    build:
      # context: ./local/ubuntu
      context: .
      dockerfile: Dockerfile.centos
    image: local-centos-image-1:latest
    ports:
      - "2222:22"
    volumes:
      - ./data:/data
    networks:
      - local-linux-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - envs/.env.ansible-server
      - envs/.env.local-centos-1

  local-ubuntu-1:
    restart: always
    # build: .
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    image: local-ubuntu-image-1:latest
    ports:
      - "2223:22"
    volumes:
      - ./data:/data
    networks:
      - local-linux-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - envs/.env.local-ubuntu-1
      - envs/.env.ubuntu


  local-ubuntu-2:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    image: local-ubuntu-image-2:latest
    ports:
      - "2224:22"
    volumes:
      - ./data:/data
    networks:
      - local-linux-network
    depends_on:
      - local-ubuntu-1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"  
    env_file:
      - envs/.env.local-ubuntu-2
      - envs/.env.ubuntu        
          

networks:
  local-linux-network:
    external: true
  # my-overlay-network:
  #   driver: overlay 
    

